[package]
name = "smartwatch"
version = "0.1.0"
authors = ["Thomas-QM <thomas@engineeringvirtue.net>"]
edition = "2018"

[dependencies]
little = {path = "../"}
little_opengl = {path = "../little-opengl"}